//! Authoring service

use crate::{Config, Hook, Runtime, Storage, Validator, storage::SyncStorage, tx};
use score::{
    BandersnatchPublic, OpaqueHash, TimeSlot,
    block::{Block, Head, Header},
    extrinsic::{TicketBody, TicketEnvelope, TicketsOrKeys},
    safrole::ValidatorIter,
};
use std::{
    collections::VecDeque,
    ops::Deref,
    sync::atomic::{AtomicU8, Ordering},
};

/// Authoring context
pub struct Author<'a, C: Config> {
    /// The runtime
    runtime: &'a Runtime<C>,

    /// The tickets generated by the current validator
    tickets: Vec<OpaqueHash>,

    /// The slots that we are authoring
    slots: VecDeque<TimeSlot>,

    /// The attempt number of the current epoch
    attempt: AtomicU8,
}

impl<'a, C: Config> Author<'a, C> {
    /// Create a new authoring context
    pub fn new(runtime: &'a Runtime<C>) -> Self {
        Self {
            runtime,
            slots: Default::default(),
            attempt: Default::default(),
            tickets: Default::default(),
        }
    }

    /// Run to the next timeslot
    pub async fn on_timeslot(
        &mut self,
        timeslot: TimeSlot,
    ) -> anyhow::Result<(Option<Header>, Option<TicketEnvelope>)> {
        let slot = timeslot % score::EPOCH_LENGTH;
        let mut next = (None, None);

        // check if the epoch is changed
        if slot == 0 {
            self.on_new_epoch().await?;
        }

        // 1. check generating tickets
        //
        // Note that we only generate tickets after two slots.
        if slot > 2 {
            if let Some((id, envelope)) = self.ticket(timeslot).await? {
                next.1 = Some(envelope);
                self.tickets.push(id);
            }
        }

        // 3. check authoring blocks
        if self.slots.contains(&slot) {
            next.0 = Some(self.author(timeslot).await?.header);
            // self.slots.pop_front();
        }

        Ok(next)
    }

    /// on new epoch
    pub async fn on_new_epoch(&mut self) -> anyhow::Result<()> {
        self.storage.on_new_epoch()?;

        // 1. reset the attempt number
        self.attempt.store(0, Ordering::Relaxed);

        // 2. clean the ticket cache
        self.expool.tickets.lock().await.clear();

        // 3. update the authoring slots
        let mut slots = VecDeque::new();
        let mut fallback = false;
        match self.storage.series()? {
            TicketsOrKeys::Tickets(tickets) => {
                for (i, ticket) in tickets.iter().enumerate() {
                    if self.tickets.contains(&ticket.id) {
                        tracing::debug!("assigned slot#{i} with ticket#{}", hex::encode(ticket.id));
                        slots.push_back(i as TimeSlot);
                    }
                }
            }
            TicketsOrKeys::Keys(keys) => {
                fallback = true;
                tracing::info!(
                    "fallback keys: {:#?}",
                    keys.iter()
                        .enumerate()
                        .map(|(i, k)| format!("{i:02} | 0x{}", hex::encode(k)))
                        .collect::<Vec<_>>()
                );
                for (i, author) in keys.iter().enumerate() {
                    if author == &self.me() {
                        slots.push_back(i as TimeSlot);
                    }
                }
            }
        }
        self.slots = slots;
        tracing::info!(
            "using {} keys, authoring slots: {:?}",
            if fallback { "fallback" } else { "safrole" },
            self.slots
        );

        self.tickets.clear();
        Ok(())
    }

    /// Author a block
    pub async fn author(&self, timeslot: TimeSlot) -> anyhow::Result<Block> {
        let keys = self.storage.current_validators()?.bandersnatch();

        // In fallback mode, verify that this validator is actually assigned to this slot
        let slot = timeslot % score::EPOCH_LENGTH;
        if let TicketsOrKeys::Keys(fallback_keys) = self.storage.series()? {
            tracing::info!(
                "fallback keys: {:#?}",
                fallback_keys
                    .iter()
                    .enumerate()
                    .map(|(i, k)| format!("{i:02} | 0x{}", hex::encode(k)))
                    .collect::<Vec<_>>()
            );

            let assigned_key = fallback_keys[slot as usize];
            if assigned_key != self.me() {
                anyhow::bail!(
                    "validator not assigned to slot {}: assigned to 0x{}, but we are 0x{}",
                    slot,
                    hex::encode(assigned_key),
                    hex::encode(self.me())
                );
            }
        }

        // 1. get the last block
        let blocks = self.storage.recent_blocks()?;
        let parent = blocks
            .last()
            .ok_or(anyhow::anyhow!("genesis block not found"))?;

        // 2. collect the extrinsics
        let envelopes = self.storage.safrole()?.accumulator;
        let extrinsic = self.expool.collect(envelopes).await?;

        // 3. init the builder
        let mut builder = Block::builder()
            .parent(parent)?
            .extrinsic(extrinsic)?
            .timeslot(timeslot);

        // 4. set the author index
        let author_index = keys
            .iter()
            .position(|v| *v == self.me())
            .ok_or_else(|| anyhow::anyhow!("validator not present in the current validator set"))?;
        builder = builder.author_index(author_index as u16);

        // 5. simulate the block
        tx::simulate::<C::Vm>(&mut builder, &self.storage)?;

        // 6. seal the block
        let block = self.seal(builder.into(), &keys)?;

        // 7. save the block to the fork storage
        self.storage.set_block(&block)?;
        self.grandpa.write().await.add_leaf(block.header.clone())?;
        let header = block.header.clone();

        // 8. notify the best block
        //
        // TODO: we have computed the hash here which is less optimized.
        self.hook.on_best_block(Head {
            hash: header.hash()?,
            slot: header.slot,
        })?;

        Ok(block)
    }

    /// Generate a ticket
    pub async fn ticket(
        &self,
        timeslot: TimeSlot,
    ) -> anyhow::Result<Option<(OpaqueHash, TicketEnvelope)>> {
        let epoch = timeslot / score::EPOCH_LENGTH;

        // 1. check if the current validator has exceeded the ticket limit
        let attempt = self.attempt.load(Ordering::Relaxed);
        if attempt >= score::TICKET_ENTRIES_PER_VALIDATOR {
            return Ok(None);
        }

        // 2. generate a ticket
        let entropy = self.storage.entropy()?;
        let next_keys = self.storage.next_validators()?.bandersnatch();
        let envelope = TicketEnvelope {
            attempt,
            signature: self.validator.bandersnatch_ring_sign(
                &next_keys,
                &[],
                &TicketBody::message(attempt, &entropy[2]),
            )?,
        };

        tracing::info!(
            "generated ticket#{} with entropy: 0x{}",
            attempt,
            hex::encode(entropy[2].as_ref())
        );

        // 3. insert the ticket into the pool
        self.attempt.fetch_add(1, Ordering::Relaxed);
        let id = self.insert_ticket(epoch, envelope.clone()).await?;
        Ok(Some((id, envelope)))
    }

    /// Seal a block
    fn seal(&self, mut block: Block, keys: &[BandersnatchPublic]) -> anyhow::Result<Block> {
        let series = self.storage.series()?;
        let entropy = self.storage.entropy()?;
        let mut keys = keys.to_vec();
        let entropy = if let Some(mark) = block.header.epoch_mark.clone() {
            keys = mark.validators.iter().map(|v| v.bandersnatch).collect();
            entropy[2]
        } else {
            entropy[3]
        };

        // construct the seal message
        let (message, ticket) = match series {
            TicketsOrKeys::Tickets(tickets) => {
                let slot = (block.header.slot % score::EPOCH_LENGTH) as usize;
                let ticket = tickets[slot];
                (TicketBody::message(ticket.attempt, &entropy), Some(ticket))
            }
            TicketsOrKeys::Keys(_) => {
                let mut message = score::JAM_FALLBACK_SEAL.to_vec();
                message.extend_from_slice(&entropy);
                (message, None)
            }
        };

        // construct the entropy source
        block.header.entropy_source = {
            let mut entropy_message = score::JAM_ENTROPY.to_vec();
            let vrf_output = self.validator.ietf_vrf_output(&message)?;
            entropy_message.extend_from_slice(&vrf_output);
            self.validator
                .bandersnatch_sign(&keys, &[], &entropy_message)?
        };

        // construct the seal
        let context = {
            let encoded = codec::encode(&block.header)?;
            encoded[..encoded.len() - 96].to_vec()
        };
        block.header.seal = self
            .runtime
            .validator
            .bandersnatch_sign(&keys, &context, &message)?;

        // verify the ticket id
        let verifier = crypto::ring::verifier(keys.clone());
        if let Some(ticket) = ticket {
            let output = verifier.ietf_vrf_verify(
                &message,
                &context,
                &block.header.seal,
                block.header.author_index as usize,
            )?;
            if output != ticket.id {
                tracing::error!(
                    "ticket seal mismatched, expected: 0x{}, got: 0x{}",
                    hex::encode(ticket.id),
                    hex::encode(output)
                );
                anyhow::bail!("ticket seal mismatched");
            }
        }

        Ok(block)
    }
}

impl<C: Config> Deref for Author<'_, C> {
    type Target = Runtime<C>;

    fn deref(&self) -> &Self::Target {
        self.runtime
    }
}

impl<C: Config> Runtime<C> {
    /// Get the authoring context
    pub fn author(&self) -> Author<C> {
        Author::new(self)
    }

    /// Sort and insert a ticket into the pool
    pub async fn insert_ticket(
        &self,
        _epoch: u32,
        ticket: TicketEnvelope,
    ) -> anyhow::Result<OpaqueHash> {
        let keys = self.storage.next_validators()?.bandersnatch();
        let entropy = self.storage.entropy()?;
        let verifier = crypto::ring::verifier(keys);
        let id = match verifier.ring_vrf_verify(
            &TicketBody::message(ticket.attempt, &entropy[2]),
            &[],
            &ticket.signature,
        ) {
            Ok(id) => id,
            Err(e) => {
                anyhow::bail!(
                    "invalid ticket#{} with entropy: 0x{}, {e}",
                    ticket.attempt,
                    hex::encode(entropy[2].as_ref()),
                );
            }
        };

        let mut tickets = self.expool.tickets.lock().await;
        tickets.insert((id, ticket));
        Ok(id)
    }
}
