[package]
name = "simple-token-service"
publish = true
authors = ["clearloop <tianyi.gc@gmail.com>"]
edition.workspace = true
repository.workspace = true
license.workspace = true
version.workspace = true
description = "The JAM Bootstrap Service, a simple swiss-army-knife service for JAM Genesis"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
podec.workspace = true
polkavm-derive.workspace = true
jam-types = { workspace = true, default-features = false }
jam-pvm-common = { workspace = true, default-features = false, features = [
    "service",
    "logging",
] }

[dev-dependencies]
pvm-testing.workspace = true

[build-dependencies]
cjam.workspace = true

[features]
default = []
tiny = ["jam-types/tiny", "jam-pvm-common/tiny"]
