[package]
name = "spacejam-offchain"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
codec.workspace = true
hyper.workspace = true
hyper-util.workspace = true
runtime.workspace = true
rpc.workspace = true
score.workspace = true
tokio.workspace = true
tracing.workspace = true
