[workspace]
members = [
    "crates/*",
    "crates/codec/erasure",
    "crates/codec/json",
    "crates/codec/json/derive",
    "crates/offchain/metrics",
    "crates/offchain/rpc",
    "crates/pvm/interpreter",
    "crates/pvm/parser",
    "crates/testing/spec",
    "jade",
    "jade/jadex",
    "jade/jadex/examples/*",
    "jade/cli", "res/jam-test-vectors/accumulate/script",
]
resolver = "1"

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
score = { path = "crates/core", package = "spacejam-core" }
codec = { path = "crates/codec", package = "jamcodec" }
crypto = { path = "crates/crypto", package = "spacejam-crypto" }
jade = { path = "jade" }
jadex = { path = "jade/jadex" }
metrics = { path = "crates/offchain/metrics", package = "spacejam-metrics" }
network = { path = "crates/network", package = "spacejam-network" }
offchain = { path = "crates/offchain", package = "spacejam-offchain" }
pvm = { path = "crates/pvm", package = "pvm" }
pvmi = { path = "crates/pvm/interpreter" }
pvm-parser = { path = "crates/pvm/parser" }
rpc = { path = "crates/offchain/rpc", package = "spacejam-rpc" }
runtime = { path = "crates/runtime", package = "runtime" }
spacejam = { path = "crates/spacejam", package = "spacejam" }
spacejson = { path = "crates/codec/json", package = "spacejson" }
spacejson-derive = { path = "crates/codec/json/derive", package = "spacejson-derive" }
specjam = { path = "crates/testing/spec", package = "specjam" }
validator = { path = "crates/spacejam/validator", package = "spacejam-validator" }

# crates.io
anyhow = "1.0.93"
ark-bls12-381 = "0.5.0"
ark-ec = { version = "0.5", default-features = false }
ark-ff = { version = "0.5", default-features = false }
ark-std = { version = "0.5", default-features = false }
ark-serialize = { version = "0.5", default-features = false }
ark-vrf = { version = "0.1.0", features = ["bandersnatch", "ring", "parallel"] }
async-graphql = "7.0.16"
async-graphql-axum = "7.0.16"
async-trait = "0.1.88"
axum = "0.8.4"
base32 = "0.5.1"
blake2 = "0.10.6"
clap = "4.5.23"
dirs = "6.0.0"
ed25519-dalek = "2.1.1"
git2 = "0.19.0"
heck = "0.5.0"
hex = "0.4.3"
hyper = "1.6"
hyper-util = "0.1.11"
jam-types = "=0.1.12"
jam-codec = "0.1.0"
jam-pvm-build = "0.1.21"
jam-pvm-builder = "0.1.21"
jam-pvm-common = "0.1.21"
jam-program-blob = "0.1.21"
jsonrpsee = "0.24.9"
once_cell = "1.20.2"
paste = "1.0.15"
parity-db = "0.5.1"
proc-macro2 = "1.0.92"
prometheus = { version = "0.23.1", package = "prometheus-client" }
prost = "0.13.0"
quinn = "0.11.6"
quote = "1.0.33"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
rcgen = "0.13.2"
reed-solomon = { package = "reed-solomon-simd", version = "3.0.1" }
ring = { package = "w3f-ring-proof", version = "0.0.2", default-features = false }
rustls = "0.23.23"
rustls-webpki = "0.102.8"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
smallvec = "1.14.0"
sqlx = "0.8.5"
syn = "2.0.90"
time = "0.3.41"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tokio = { version = "1.42.0", features = ["rt", "sync", "net", "macros"] }
tokio-stream = "0.1.17"
toml = "0.8.19"
tonic = "0.13"
tonic-build = "0.13"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
trait-variant = "0.1.2"
uint = "0.10.0"
w3f-bls = "0.1.8"
x509-parser = "0.17.0"

[patch.crates-io]
async-graphql = { version = "7.0.16", git = "https://github.com/yasamoka/async-graphql.git", branch = "graphiqlsource-react" }

[profile.release]
debug = false
strip = true
lto = true
opt-level = "z"
panic = "abort"
