[workspace]
members = ["crates/*", "crates/codec/derive"]
resolver = "1"

[workspace.dependencies]
core = { path = "crates/core", package = "spacejam-core" }
codec = { path = "crates/codec", package = "jamcodec" }
codec-derive = { path = "crates/codec/derive", package = "jamcodec-derive" }
trie = { path = "crates/trie", package = "spacejam-trie" }

# crates.io
anyhow = "1.0.93"
blake2 = "0.10.6"
git2 = "0.19.0"
hex = "0.4.3"
paste = "1.0.15"
proc-macro2 = "1.0.92"
quote = "1.0.33"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
syn = "2.0.90"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
