[package]
name = "spacejam-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
codec.workspace = true
crypto = { workspace = true, features = ["shuffle", "vrf"] }
hex.workspace = true
pvm.workspace = true
score = { workspace = true, features = ["crypto"] }
serde.workspace = true
serde_json.workspace = true
spacejson.workspace = true
tokio.workspace = true
tracing.workspace = true
