[package]
name = "spacejam-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
account = { workspace = true, features = [
    "ed25519",
    "merkle",
    "shuffle",
    "vrf",
] }
anyhow.workspace = true
codec.workspace = true
crypto = { workspace = true, features = ["vrf", "merkle"] }
erasure.workspace = true
hex.workspace = true
once_cell.workspace = true
pvm.workspace = true
score.workspace = true
serde.workspace = true
serde_json.workspace = true
spacejson.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = ["timing"]
timing = []
