//! Authoring service

use crate::{
    storage::{StateStorage, SyncStorage},
    tx, Config, Runtime, Validator,
};
use anyhow::Context;
use score::{
    block::{Block, Header},
    extrinsic::{ticket, Ticket, TicketBody, TicketEnvelope, TicketsOrKeys},
    safrole::ValidatorIter,
    BandersnatchPublic, OpaqueHash, TimeSlot,
};
use std::{
    ops::Deref,
    sync::atomic::{AtomicU8, Ordering},
};

/// Authoring context
pub struct Author<'a, C: Config> {
    /// The runtime
    runtime: &'a Runtime<C>,

    /// The tickets generated by the current validator
    tickets: Vec<OpaqueHash>,

    /// The slots that we are authoring
    pub slots: Vec<TimeSlot>,

    /// The attempt number of the current epoch
    attempt: AtomicU8,

    /// The epoch of the current authoring
    epoch: u32,
}

impl<'a, C: Config> Author<'a, C> {
    /// Create a new authoring context
    pub fn new(runtime: &'a Runtime<C>) -> Self {
        Self {
            runtime,
            slots: Default::default(),
            attempt: Default::default(),
            tickets: Default::default(),
            epoch: 0,
        }
    }

    /// Run to the next timeslot
    pub async fn on_timeslot(
        &mut self,
        timeslot: TimeSlot,
    ) -> anyhow::Result<(Option<Header>, Option<Ticket>)> {
        let best = self.chain.read().await.best()?;
        let slot = timeslot % score::EPOCH_LENGTH;
        let epoch = timeslot / score::EPOCH_LENGTH;
        let prev = best.slot / score::EPOCH_LENGTH;
        let mut next = (None, None);

        // check if the epoch is changed
        if epoch > prev && epoch > self.epoch {
            self.on_new_epoch(epoch).await?;
        }

        // 1. check generating tickets
        let finalized = self.storage.finalized()?;
        if ticket::generate(slot, best.slot, finalized.slot) {
            if let Some(ticket) = self.ticket(best.slot).await? {
                self.tickets.push(ticket.id);
                next.1 = Some(ticket);
            }
        }

        // 2. check authoring blocks
        if self.slots.contains(&slot) {
            next.0 = Some(self.author(timeslot).await?.header);
            self.slots.retain(|s| *s != slot);
        }

        Ok(next)
    }

    /// on new epoch
    pub async fn on_new_epoch(&mut self, epoch: u32) -> anyhow::Result<()> {
        // 1. reset the attempt number
        self.attempt.store(0, Ordering::Relaxed);

        // 2. clean the ticket cache
        self.runtime.tickets.lock().await.clear();
        self.expool.tickets.lock().await.clear();

        // 3. update the authoring slots
        let mut slots = Vec::new();
        let mut fallback = false;
        match self.chain.read().await.series(epoch)? {
            TicketsOrKeys::Tickets(tickets) => {
                for (i, ticket) in tickets.iter().enumerate() {
                    if self.tickets.contains(&ticket.id) {
                        tracing::debug!("assigned slot#{i} with ticket#{}", hex::encode(ticket.id));
                        slots.push(i as TimeSlot);
                    }
                }
            }
            TicketsOrKeys::Keys(keys) => {
                fallback = true;
                tracing::trace!(
                    "fallback keys: {:#?}",
                    keys.iter()
                        .enumerate()
                        .map(|(i, k)| format!("{i:02} | 0x{}", hex::encode(k)))
                        .collect::<Vec<_>>()
                );
                for (i, author) in keys.iter().enumerate() {
                    if author == &self.me() {
                        slots.push(i as TimeSlot);
                    }
                }
            }
        }
        self.slots = slots;
        tracing::info!(
            "epoch={epoch} using {} keys, authoring slots: {:?}",
            if fallback { "fallback" } else { "safrole" },
            self.slots
        );

        self.tickets.clear();
        self.epoch = epoch;
        Ok(())
    }

    /// Author a block
    pub async fn author(&self, timeslot: TimeSlot) -> anyhow::Result<Block> {
        let keys = self.storage.current_validators()?.bandersnatch();

        // 1. get the last block
        let blocks = self.storage.recent_blocks()?;
        let mut parent = blocks
            .last()
            .ok_or(anyhow::anyhow!("genesis block not found"))?
            .clone();

        // 2. collect the extrinsics
        let envelopes = self.storage.safrole()?.accumulator;
        let extrinsic = self.expool.collect(envelopes).await?;

        // 3. init the builder
        parent.state_root = self.storage.root()?;
        let mut builder = Block::builder()
            .parent(&parent)?
            .extrinsic(extrinsic)?
            .timeslot(timeslot);

        // 4. set the author index
        let author_index = keys
            .iter()
            .position(|v| *v == self.me())
            .ok_or_else(|| anyhow::anyhow!("validator not present in the current validator set"))?;
        builder = builder.author_index(author_index as u16);

        // 5. simulate the block
        //
        // FIXME:
        //
        // do not simulate the block but just calculate the required data
        let _diff = tx::simulate::<C::Vm>(&mut builder, self.storage.clone())?;
        let block: Block = builder.into();

        // 6. seal the block
        let block = self.seal(block, &keys).await?;

        // 7. save the block to the fork storage
        //
        // FIXME: import block here.
        Ok(block)
    }

    /// Generate a ticket
    #[tracing::instrument(skip_all, name = "ticket::generate")]
    pub async fn ticket(&self, timeslot: TimeSlot) -> anyhow::Result<Option<Ticket>> {
        let epoch = timeslot / score::EPOCH_LENGTH;

        // 1. check if the current validator has exceeded the ticket limit
        let attempt = self.attempt.load(Ordering::Relaxed);
        if attempt > score::TICKET_ENTRIES_PER_VALIDATOR as u8 {
            return Ok(None);
        }

        // 2. generate a ticket
        let entropy = self.storage.entropy()?;
        let next_keys = self.storage.next_validators()?.bandersnatch();
        let envelope = TicketEnvelope {
            attempt,
            signature: self.validator.bandersnatch_ring_sign(
                &next_keys,
                &[],
                &TicketBody::message(attempt, &entropy[2]),
            )?,
        };

        tracing::info!(
            "generated ticket#{} with entropy: 0x{}",
            attempt,
            hex::encode(entropy[2].as_ref())
        );

        // 3. insert the ticket into the pool
        self.attempt.fetch_add(1, Ordering::Relaxed);
        let ticket = self.verify_ticket(envelope).await?;
        self.insert_ticket(epoch, ticket.clone()).await?;
        Ok(Some(ticket))
    }

    /// Seal a block
    #[tracing::instrument(skip_all, name = "seal")]
    async fn seal(&self, mut block: Block, keys: &[BandersnatchPublic]) -> anyhow::Result<Block> {
        let entropy = self.storage.entropy()?;
        let mut keys = keys.to_vec();
        let entropy = if let Some(mark) = block.header.epoch_mark.clone() {
            keys = mark.validators.iter().map(|v| v.bandersnatch).collect();
            entropy[2]
        } else {
            entropy[3]
        };

        // construct the seal message
        let epoch = block.header.slot / score::EPOCH_LENGTH;
        let series = self.chain.read().await.series(epoch)?;
        let (message, ticket) = match series {
            TicketsOrKeys::Tickets(tickets) => {
                let slot = (block.header.slot % score::EPOCH_LENGTH) as usize;
                let ticket = tickets[slot];
                (TicketBody::message(ticket.attempt, &entropy), Some(ticket))
            }
            TicketsOrKeys::Keys(_) => {
                let mut message = score::JAM_FALLBACK_SEAL.to_vec();
                message.extend_from_slice(&entropy);
                (message, None)
            }
        };

        // construct the entropy source
        block.header.entropy_source = {
            let mut entropy_message = score::JAM_ENTROPY.to_vec();
            let vrf_output = self.validator.ietf_vrf_output(&message)?;
            entropy_message.extend_from_slice(&vrf_output);
            self.validator
                .bandersnatch_sign(&keys, &[], &entropy_message)?
        };

        // construct the seal
        let context = {
            let encoded = codec::encode(&block.header)?;
            encoded[..encoded.len() - 96].to_vec()
        };
        block.header.seal = self
            .runtime
            .validator
            .bandersnatch_sign(&keys, &context, &message)?;

        // verify the ticket id
        let verifier = crypto::ring::verifier(keys.clone());
        if let Some(ticket) = ticket {
            let output = verifier
                .ietf_vrf_verify(
                    &message,
                    &context,
                    &block.header.seal,
                    block.header.author_index as usize,
                )
                .context("failed to verify the ticket id")?;
            if output != ticket.id {
                tracing::error!(
                    "ticket seal mismatched, expected: 0x{}, got: 0x{}",
                    hex::encode(ticket.id),
                    hex::encode(output)
                );
                anyhow::bail!("ticket seal mismatched");
            }
        }

        Ok(block)
    }
}

impl<C: Config> Deref for Author<'_, C> {
    type Target = Runtime<C>;

    fn deref(&self) -> &Self::Target {
        self.runtime
    }
}

impl<C: Config> Runtime<C> {
    /// Get the authoring context
    pub fn author(&self) -> Author<C> {
        Author::new(self)
    }

    /// Verify a ticket
    pub async fn verify_ticket(&self, ticket: TicketEnvelope) -> anyhow::Result<Ticket> {
        let keys = self.storage.next_validators()?.bandersnatch();
        let entropy = self.storage.entropy()?;
        let verifier = crypto::ring::verifier(keys);
        let id = verifier
            .ring_vrf_verify(
                &TicketBody::message(ticket.attempt, &entropy[2]),
                &[],
                &ticket.signature,
            )
            .context("failed to verify the ticket")?;

        Ok(Ticket {
            id,
            envelope: ticket,
        })
    }

    /// Sort and insert a ticket into the pool
    pub async fn insert_ticket(&self, _epoch: u32, ticket: Ticket) -> anyhow::Result<()> {
        let mut tickets = self.expool.tickets.lock().await;
        tickets.insert(ticket);
        Ok(())
    }
}
