[package]
name = "spacejson"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
hex = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["alloc"] }
spacejson-derive.workspace = true

[features]
default = []
std = ["anyhow/std", "hex/std", "serde/std"]
