[package]
name = "spacejam-service"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Service types in SpaceJam"
documentation = "https://docs.rs/spacejam-service"
categories = ["no-std", "embedded"]
keywords = ["pvm"]

[dependencies]
anyhow.workspace = true
codec.workspace = true
serde.workspace = true
spec.workspace = true

# optional dependencies
blake2 = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
serde_json = { workspace = true, features = ["alloc"], optional = true }
spacejson = { workspace = true, optional = true }

[features]
default = ["std", "tiny"]
std = [
    "anyhow/std",
    "blake2?/std",
    "codec/std",
    "hex/std",
    "serde/std",
    "serde_json/std",
    "spacejson?/std",
]
blake2 = ["dep:blake2"]
json = ["hex", "serde_json", "spacejson", "spacejson/codec"]
tiny = ["spec/tiny"]
full = ["spec/full"]
