[package]
name = "pvm"
version = "0.0.0"
edition = "2021"
description = "Polkadot Virtual Machine"

[dependencies]
anyhow.workspace = true
codec.workspace = true
crypto = { workspace = true, features = ["blake2"] }
hex.workspace = true
log.workspace = true
score = { workspace = true, features = ["crypto"] }
tracing.workspace = true
pvm-parser.workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }
