[package]
name = "spacerpc"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper.workspace = true
hyper-util.workspace = true
score.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
tower.workspace = true
tower-layer.workspace = true
tower-service.workspace = true
