[package]
name = "pvm-testing"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
name = "testing"

[dependencies]
anyhow.workspace = true
worker.workspace = true
cjam.workspace = true
etc.workspace = true
podec.workspace = true
pvm.workspace = true
pvmi.workspace = true
score = { workspace = true, features = ["blake2"] }
score-ext = { workspace = true, features = ["blake2"] }
tracing.workspace = true
tracing-subscriber.workspace = true
