//! Primitives for the accumulate invocation

use crate::{BTreeMap, Gas, OpaqueHash, ServiceId, Vec, service::WorkExecResult};
use serde::{Deserialize, Serialize};

/// The commitment map
pub type CommitmentMap = BTreeMap<ServiceId, OpaqueHash>;

impl From<Operand> for AccumulateItem {
    fn from(operand: Operand) -> Self {
        AccumulateItem::Operand(operand)
    }
}

impl From<DeferredTransfer> for AccumulateItem {
    fn from(transfer: DeferredTransfer) -> Self {
        AccumulateItem::Transfer(transfer)
    }
}

/// The accumulate params for the accumulation
#[derive(Serialize, Deserialize, Debug)]
pub struct AccumulateParams {
    /// (N_t)  timeslot for the current accumulation
    #[serde(with = "codec::compact")]
    pub slot: u32,

    /// (N_s)  the service id of the caller
    #[serde(with = "codec::compact")]
    pub id: u32,

    /// (|o|) The count of operands
    #[serde(with = "codec::compact")]
    pub results: u32,
}

/// An item of the accumulation
///
/// reference per GP (C.33)
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum AccumulateItem {
    /// The operands (12.13) + (C.32)
    Operand(Operand),

    /// The deferred transfers (12.14) + (C.31)
    Transfer(DeferredTransfer),
}

/// An operand of the accumulation
///
/// NOTE: we are currently following the order of jam-types instead
/// of graypaper.
///
/// defined per GP (12.13), (C.32) for the order.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Operand {
    /// (p) The hash of the work package
    pub package: OpaqueHash,

    /// (e) The root of the segment tree which was generated by the work-package
    /// in which the work-item which gave this result was placed.
    pub exports_root: OpaqueHash,

    /// (a) The hash of the authorizer which authorized the execution of the
    /// work-package which generated this result.
    pub authorizer_hash: OpaqueHash,

    /// (y) The payload blob hash
    pub payload: OpaqueHash,

    /// (g) The accumulate gas
    #[serde(with = "codec::compact")]
    pub gas: Gas,

    /// (l) The work execution result
    pub data: WorkExecResult,

    /// (t) The output of the Is-Authorized logic which authorized the execution
    /// of the work-package which generated this result.
    pub auth_output: Vec<u8>,
}

/// (12.14) A deferred transfer item (encoding: C.31)
#[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
pub struct DeferredTransfer {
    /// (s) The sender
    pub sender: ServiceId,

    /// (d) The destination
    pub recipient: ServiceId,

    /// (a) The amount
    pub amount: u64,

    /// (m) The memo
    #[serde(with = "codec::bytes")]
    pub memo: [u8; crate::TRANSFER_MEMO_SIZE],

    /// (g) The gas limit
    pub gas_limit: Gas,
}

impl DeferredTransfer {
    /// (R): Select transfers for a given destination service
    pub fn select(transfers: &[DeferredTransfer], dest: ServiceId) -> Vec<DeferredTransfer> {
        let mut transfers = transfers.to_vec();
        transfers.sort_by_key(|t| t.sender);
        transfers
            .iter()
            .filter(|t| t.recipient == dest)
            .cloned()
            .collect()
    }
}
