//! Primitives for the accumulate invocation

use crate::{
    BTreeMap, Gas, OpaqueHash, ServiceId, Vec, service::WorkExecResult, vm::DeferredTransfer,
};
use serde::{Deserialize, Serialize};

/// The commitment map
pub type CommitmentMap = BTreeMap<ServiceId, OpaqueHash>;

/// The accumulate params for the accumulation
#[derive(Serialize, Deserialize, Debug)]
pub struct AccumulateParams {
    /// (N_t)  timeslot for the current accumulation
    #[serde(with = "codec::compact")]
    pub slot: u32,

    /// (N_s)  the service id of the caller
    #[serde(with = "codec::compact")]
    pub id: u32,

    /// (|o|) The count of operands
    #[serde(with = "codec::compact")]
    pub results: u32,
}

/// An operand of the accumulation
///
/// NOTE: we are currently following the order of jam-types instead
/// of graypaper.
///
/// defined per GP (12.13), (C.32) for the order.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Operand {
    /// (p) The hash of the work package
    pub package: OpaqueHash,

    /// (e) The root of the segment tree which was generated by the work-package
    /// in which the work-item which gave this result was placed.
    pub exports_root: OpaqueHash,

    /// (a) The hash of the authorizer which authorized the execution of the
    /// work-package which generated this result.
    pub authorizer_hash: OpaqueHash,

    /// (y) The payload blob hash
    pub payload: OpaqueHash,

    /// (g) The accumulate gas
    #[serde(with = "codec::compact")]
    pub gas: Gas,

    /// (l) The work execution result
    pub data: WorkExecResult,

    /// (t) The output of the Is-Authorized logic which authorized the execution
    /// of the work-package which generated this result.
    pub auth_output: Vec<u8>,
}

/// An item of the accumulation
///
/// reference per GP (C.33)
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum AccumulateItem {
    /// The operands (12.13) + (C.32)
    Operand(Operand),

    /// The deferred transfers (12.14) + (C.31)
    Transfer(DeferredTransfer),
}

impl From<Operand> for AccumulateItem {
    fn from(operand: Operand) -> Self {
        AccumulateItem::Operand(operand)
    }
}

impl From<DeferredTransfer> for AccumulateItem {
    fn from(transfer: DeferredTransfer) -> Self {
        AccumulateItem::Transfer(transfer)
    }
}
