[package]
name = "serde-jam"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "JAM encoding with serde"
documentation = "https://docs.rs/serde-jam"

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["alloc"] }

[features]
default = []
std = ["anyhow/std", "serde/std"]
