# docker compose config for local tiny network.

services:
  polkajam-0:
    image: polkajam:0.1.23
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 0 --port 40000 --rpc-port 19800 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/0:/data
    environment:
      - RUST_LOG=jam_node=trace
  polkajam-1:
    image: polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 1 --port 40001 --rpc-port 19801 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/1:/data
    environment:
      - RUST_LOG=jam_node=trace
  polkajam-2:
    image: polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 2 --port 40002 --rpc-port 19802 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/2:/data
    environment:
      - RUST_LOG=jam_node=trace
  polkajam-3:
    image: polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 3 --port 40003 --rpc-port 19803 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/3:/data
    environment:
      - RUST_LOG=jam_node=trace
  polkajam-4:
    image: polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 4 --port 40004 --rpc-port 19804 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/4:/data
    environment:
      - RUST_LOG=jam_node=trace
  spacejam:
    image: spacejam:0.0.1
    depends_on:
      - polkajam-0
    network_mode: host
    command: run -d /data --chain /shared/spec.json --validator 5 --address 127.0.0.1:40005
    volumes:
      - ./data:/shared
      - ./node/5:/data
    environment:
      - RUST_LOG=spacejam,runtime,network=trace

# Using host networking mode - no custom network needed
