version: '3.8'

services:
  spacejam-1:
    image: clearloop/spacejam:latest
    command: spawn --validator 0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a
    networks: ["spacenet"]
    volumes: [res/node/1:/data]
  spacejam-2:
    image: clearloop/spacejam:latest
    command: spawn --validator 1
    networks: ["spacenet"]
    volumes: [res/node/2:/data]
  spacejam-3:
    image: clearloop/spacejam:latest
    command: spawn --validator 2
    networks: ["spacenet"]
    volumes: [res/node/3:/data]
  spacejam-4:
    image: clearloop/spacejam:latest
    command: spawn --validator 3
    networks: ["spacenet"]
    volumes: [res/node/4:/data]
  spacejam-5:
    image: clearloop/spacejam:latest
    command: spawn --validator 4
    networks: ["spacenet"]
    volumes: [res/node/5:/data]
  spacejam-6:
    image: clearloop/spacejam:latest
    command: spawn --validator 5
    networks: ["spacenet"]
    volumes: [res/node/6:/data]

networks:
  spacenet:
    driver: bridge
