[package]
name = "spacejam-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonrpsee = { workspace = true, features = ["macros"] }
score.workspace = true
serde.workspace = true

# server dependencies
tracing = { workspace = true, optional = true }

[features]
default = ["client", "server"]
client = ["jsonrpsee/client"]
server = ["jsonrpsee/server", "tracing"]
