//! Block sync validation

use anyhow::Result;
use score::{Block, State};

pub mod assurance;
pub mod dispute;
pub mod guarantee;
pub mod preimage;
pub mod statistic;
pub mod ticket;

/// Block sync validation result
pub struct Sync;

/// Validate new block and transit to the next state.
///
/// - the argument entropy should be generated by the validator (6.22)
///
/// WARNING: DO NOT change the order of the state transition logic unless you
///          follow the dependency graph: GP 4.2.1
///
/// TODO: keep splitting logic inside of validation logic
pub fn transit(block: &Block, state: &State, entropy: [u8; 32]) -> Result<Sync> {
    let mut next = state.clone();

    let (_epoch, _tickets) = ticket::validate(&mut next, block, entropy)?;
    assurance::validate(&mut next, block)?;

    // TODO: enable dispute validation interface
    //
    // dispute::validate(&mut next, block)?;
    next.timeslot = block.header.slot;
    preimage::validate(&mut next, block)?;
    guarantee::validate(&mut next, block)
        .map_err(|_| anyhow::anyhow!("Failed to validate guarantee"))?;
    statistic::validate(&mut next, block);
    Ok(Sync)
}
