[package]
name = "jade-core"
version.workspace = true
edition.workspace = true
description = "SpaceJam shared types for the Jade framework"

[dependencies]
anyhow.workspace = true
blake2 = { workspace = true, optional = true }
codec.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
spacejson.workspace = true

[features]
default = []
blake2 = ["dep:blake2"]
