[package]
name = "spacejson-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Derive JSON interfaces for types"
documentation = "https://docs.rs/spacejson-derive"
categories = ["no-std", "encoding"]
keywords = ["json", "serde"]

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
proc-macro2.workspace = true
quote.workspace = true
