[package]
name = "spacejam-builder"
version.workspace = true
edition.workspace = true
description = "Spacejam work package builder"

[lib]
path = "src/lib.rs"
name = "builder"

[dependencies]
score.workspace = true
crypto = { workspace = true, features = ["blake2"] }
codec.workspace = true
spacejson.workspace = true
anyhow.workspace = true
