[package]
name = "spacejam"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "spacejam"
path = "bin/spacejam.rs"
required-features = ["node"]

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"], optional = true }
codec.workspace = true
crypto.workspace = true
hex.workspace = true
hyper = { workspace = true, optional = true, features = ["server", "http2"] }
hyper-util = { workspace = true, optional = true, features = ["tokio"] }
metrics = { workspace = true, optional = true }
network.workspace = true
rocksdb = { workspace = true, optional = true }
rand.workspace = true
score = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sled = { workspace = true, optional = true }
spacejson = { workspace = true, optional = true }
sync.workspace = true
toml = { workspace = true, optional = true }
tokio = { workspace = true, features = [
    "rt",
    "sync",
    "net",
    "macros",
    "signal",
] }
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }

[features]
bin = ["node", "sled"]
cmd = ["clap", "serde", "spacejson", "network/cmd"]
default = ["bin", "metrics", "serde"]
metrics = ["hyper", "hyper-util", "dep:metrics"]
node = ["cmd", "tracing-subscriber"]
serde = ["dep:serde", "serde_json", "toml"]
