[package]
name = "spacejam"
version.workspace = true
edition.workspace = true

[[bin]]
name = "spacejam"
path = "bin/spacejam.rs"
required-features = ["node"]

[dependencies]
account.workspace = true
anyhow.workspace = true
async-trait.workspace = true
clap = { workspace = true, features = ["derive", "env"], optional = true }
codec.workspace = true
crypto.workspace = true
dirs.workspace = true
hex.workspace = true
network.workspace = true
offchain.workspace = true
parity-db.workspace = true
spacevm.workspace = true
rand.workspace = true
rayon.workspace = true
runtime.workspace = true
score = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
spacejson = { workspace = true, optional = true }
testing.workspace = true
time = { workspace = true, optional = true, features = ["local-offset"] }
toml = { workspace = true, optional = true }
tokio = { workspace = true, features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "net",
    "macros",
    "signal",
] }
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true, features = [
    "fmt",
    "time",
] }

[dev-dependencies]
temp-dir.workspace = true

[build-dependencies]
syn.workspace = true
proc-macro2.workspace = true
quote.workspace = true

[features]
bin = ["node"]
cmd = [
    "clap",
    "network/cmd",
    "serde",
    "spacejson",
    "time",
    "tracing-subscriber",
]
default = ["bin", "serde"]
node = ["cmd"]
serde = [
    "dep:serde",
    "serde_json",
    "toml",
    "crypto/bls",
    "crypto/ed25519",
    "crypto/vrf",
]
