[package]
name = "spacejam-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
codec.workspace = true
crypto = { workspace = true, optional = true }
hex.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
spacejson.workspace = true
tokio.workspace = true

[features]
default = []
ed25519 = ["crypto/ed25519"]
merkle = ["crypto/merkle"]
blake2 = ["crypto/blake2"]
shuffle = ["crypto/shuffle"]
vrf = ["crypto/vrf"]
