[package]
name = "spacejam-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
codec.workspace = true
erased-serde.workspace = true
hex.workspace = true
service = { workspace = true, features = ["json"] }
tracing.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
spacejson = { workspace = true, features = ["codec"] }

[features]
default = ["blake2", "tiny"]
blake2 = ["service/blake2"]
tiny = ["service/tiny"]
full = ["service/full"]
