[book]
authors = ["clearloop"]
language = "en"
multilingual = false
src = "src"
title = "SpaceJam"

[output.html]
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]
playground = { runnable = false }

[preprocessor.mermaid]
command = "mdbook-mermaid"
