[book]
authors = ["clearloop"]
language = "en"
multilingual = false
src = "src"
title = "SpaceJam"

[output.html.fold]
# enable = true

[output.html.playground]
runnable = false

[output.html.print]
enable = true
page-break = true
