[package]
name = "spacejam-testing"
version = "0.0.0"
edition = "2021"


[dev-dependencies]
anyhow.workspace = true
assurance.workspace = true
codec.workspace = true
crypto.workspace = true
dispute.workspace = true
hex.workspace = true
merkle.workspace = true
paste.workspace = true
preimage.workspace = true
pvmi.workspace = true
report.workspace = true
spacejam.workspace = true
safrole.workspace = true
score.workspace = true
serde.workspace = true
serde_json.workspace = true
spacejson.workspace = true
statistic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true


[build-dependencies]
anyhow.workspace = true
git2.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
