[package]
name = "spacejam-testing"
version = "0.0.0"
edition = "2021"

[dependencies]
tracing-subscriber.workspace = true

[dev-dependencies]
anyhow.workspace = true
codec.workspace = true
crypto.workspace = true
dispute.workspace = true
hex.workspace = true
paste.workspace = true
report.workspace = true
spacejam.workspace = true
safrole.workspace = true
score.workspace = true
serde.workspace = true
serde_json.workspace = true
spacejson.workspace = true
merkle.workspace = true
stats.workspace = true

[build-dependencies]
anyhow.workspace = true
git2.workspace = true
