[package]
name = "pvmc"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
crypto = { workspace = true, features = ["blake3"] }
dirs.workspace = true
hex.workspace = true
postcard.workspace = true
pvm.workspace = true
translator.workspace = true
cranelift = { workspace = true, features = [
    "native",
    "jit",
    "module",
    "object",
] }
cranelift-codegen = { workspace = true, features = ["incremental-cache"] }
tracing.workspace = true
libc.workspace = true

[dev-dependencies]
libc.workspace = true
specjam.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
cc.workspace = true
bindgen.workspace = true
