[package]
name = "pvmc"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
hex.workspace = true
postcard.workspace = true
pvm.workspace = true
translator.workspace = true
cranelift.workspace = true
cranelift-codegen = { workspace = true, features = [
    "incremental-cache",
    "serde",
] }
cranelift-native.workspace = true
cranelift-jit.workspace = true
cranelift-module.workspace = true
cranelift-object.workspace = true
tracing.workspace = true
libc.workspace = true

[dev-dependencies]
libc.workspace = true
specjam.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
cc.workspace = true
bindgen.workspace = true
