[package]
name = "pvmc"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cranelift.workspace = true
cranelift-codegen.workspace = true
cranelift-frontend.workspace = true
cranelift-native.workspace = true
pvm.workspace = true
pvm-parser.workspace = true
pvmi.workspace = true
anyhow.workspace = true
tracing.workspace = true
codec.workspace = true
serde.workspace = true
libc = "0.2"

[build-dependencies]
anyhow.workspace = true
proc-macro2.workspace = true
quote.workspace = true
specjam.workspace = true
syn.workspace = true

[dev-dependencies]
specjam.workspace = true
serde.workspace = true
serde_json.workspace = true
