[package]
name = "spacejam-crypto"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true, optional = true }
ark-ec = { workspace = true, optional = true }
ark-ed-on-bls12-381-bandersnatch = { workspace = true, optional = true }
ark-serialize = { workspace = true, optional = true }
ark-vrf = { workspace = true, optional = true }
blake2 = { workspace = true, optional = true }
blake3 = { workspace = true, optional = true }
ed25519-zebra = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
rcgen = { workspace = true, optional = true }
ring = { workspace = true, optional = true }
tiny-keccak = { workspace = true, optional = true }
w3f-bls = { workspace = true, optional = true }
tracing.workspace = true

[features]
default = []
full = []
blake2 = ["dep:blake2"]
blake3 = ["dep:blake3"]
bls = ["w3f-bls"]
ed25519 = ["anyhow", "ed25519-zebra", "rand", "rayon"]
keccak = ["tiny-keccak"]
merkle = ["blake2", "keccak", "rayon"]
rand = ["dep:rand"]
shuffle = ["blake2"]
tls = ["rcgen", "ed25519-zebra/pkcs8"]
vrf = [
    "anyhow",
    "ark-vrf",
    "ark-ec",
    "ark-ed-on-bls12-381-bandersnatch",
    "ark-serialize",
    "once_cell",
    "ring",
]

[dev-dependencies]
criterion = { version = "0.5", default-features = false }
hex = { workspace = true, features = ["std"] }
serde.workspace = true
serde_json = { workspace = true, features = ["std"] }

[[bench]]
name = "ed25519"
harness = false
required-features = ["ed25519"]

[build-dependencies]
ark-serialize.workspace = true
ark-vrf.workspace = true
