[package]
name = "spacejam-crypto"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
ark-bls12-381.workspace = true
ark-ec.workspace = true
ark-ec-vrfs.workspace = true
ark-ff.workspace = true
ark-serialize.workspace = true
ark-std.workspace = true
blake2.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
once_cell.workspace = true
ring.workspace = true
tiny-keccak.workspace = true
tracing.workspace = true

[build-dependencies]
anyhow.workspace = true
git2.workspace = true
