[package]
name = "spacejam-network"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
base32.workspace = true
clap = { workspace = true, features = ["derive"], optional = true }
crypto.workspace = true
litep2p = { workspace = true, features = ["quic"] }
metrics.workspace = true
once_cell.workspace = true
quinn.workspace = true
rcgen = { workspace = true, features = ["x509-parser"] }
rustls.workspace = true
rustls-webpki.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }
x509-parser.workspace = true

[features]
default = ["bin"]
cmd = ["clap"]
bin = ["clap", "tracing-subscriber"]
