[package]
name = "spacejam-network"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
crypto.workspace = true
quinn.workspace = true
quinn-proto.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
score.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
